# Generated by Django 4.2.9 on 2024-05-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='data_source',
            field=models.CharField(default='csv', max_length=10),
        ),
    ]
