# Generated by Django 4.2.9 on 2024-05-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tenant_data_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='start_date',
        ),
        migrations.AddField(
            model_name='salesdata',
            name='month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='product_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='year',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
